name: PlayerStats
main: PlayerStats\PlayerStats
version: 2.1.1
author: xpyctum
api: [2.0.0]
load: POSTWORLD
commands:
 stats:
  default: true
  usage: "/stats <user>"
  permissions: playerstats.command
permissions:
 playerstats.command:
  default: true
